---
sidebar: sidebar
permalink: reference-azure-support.html
keywords: microsoft azure, azure, hot, access tier, cold, regions, cloud tiering, tier, bluexp
summary: NetApp Cloud Tiering supports two access tiers and most regions.
---

= Supported Azure Blob access tiers and regions for NetApp Cloud Tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Cloud Tiering supports two access tiers and most regions.

== Supported Azure Blob access tiers

When you set up data tiering to Azure from your on-premises ONTAP systems, Cloud Tiering automatically uses the _Hot_ access tier for your inactive data. Cloud Tiering can apply a lifecycle rule so the data transitions from the _Hot_ access tier to the _Cool_ access tier after a certain number of days.

If you do not choose the _Cool_ access tier, then the data remains in the _Hot_ access tier and no rules are applied.

When you configure a Cloud Tiering lifecycle rule, you must not configure any lifecycle rules when setting up the container in your Azure account.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview[Learn about Azure Blob access tiers^].

== Supported Azure regions


Cloud Tiering is supported in all Azure Regions except for China, where Microsoft Azure operated by 21Vianet.

