---
sidebar: sidebar
permalink: task-licensing-cloud-tiering.html
keywords: subscribe, digital wallet, trial, marketplace, subscription, paygo, pay as you go, byol, bring your own license, annual, tiering, cloud tiering, license, cloud tiering, bluexp
summary: A 30-day free trial of NetApp Cloud Tiering starts when you set up tiering from your first cluster. After the free trial ends, you'll need to pay for Cloud Tiering through a pay-as-you-go or annual subscription from your cloud provider's marketplace, a BYOL license from NetApp, or a combination of both.
---

= Set up licensing for NetApp Cloud Tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Cloud Tiering is no longer available for purchase or license renewal as of April 26, 2026. 

include::_include/cloud-tiering-eol.adoc[]

If you are currently using Cloud Tiering licensing, you're not affected until your Cloud Tiering license reaches its expiration date or maximum capacity. Contact NetApp when you need to update your license, or earlier to make sure there is no interruption in your ability to tier data to the cloud.



[[cloud-tiering-byol-licensing-starting-in-2021]]
== Move from NetApp Cloud Tiering to FabricPool licensing

Tiering data is supported only with an ONTAP FabricPool license. You'll need to install a FabricPool license on each ONTAP cluster using the ONTAP CLI.

Customer question:: How does one enable tiering for Azure NetApp Files, CVO and others? Still with the CLI? I'm confused on how these are different from ONTAP in their management.

Customer question:: Can customers tier to Amazon S3, Azure Blob storage, Google Cloud Storage, NetApp StorageGRID, and S3-compatible object storage. Is this covered in the ONTAP docs?

NOTE: You must use the ONTAP CLI to install a FabricPool license. You cannot use System Manager. However, once the license is installed, you can manage FabricPool either through the CLI or System Manager.



A *FabricPool* license that you may have used in the past to tier on-premises ONTAP data to the cloud is being retained only for ONTAP deployments in sites that have no internet access (also known as "dark sites"), and for tiering configurations to IBM Cloud Object Storage. If you're using this type of configuration, you'll install a FabricPool license on each cluster using the ONTAP CLI.

TIP: Note that tiering to StorageGRID does not require a FabricPool license.

If you are currently using Cloud Tiering licensing, you're not affected until your Cloud Tiering license reaches its expiration date or maximum capacity. Contact NetApp when you need to update your license, or earlier to make sure there is no interruption in your ability to tier data to the cloud.

* If you're using a configuration that's supported in the Console, your FabricPool licenses will be converted to Cloud Tiering licenses and they'll appear in the Console. When those initial licenses expire, you'll need to update the Cloud Tiering licenses.
* If you're using a configuration that's not supported in the Console, then you'll continue using a FabricPool license. https://docs.netapp.com/us-en/ontap/cloud-install-fabricpool-task.html[See how to license tiering using System Manager^].

Here are some things you need to know about the two licenses:

[cols="50,50",width=95%,options="header"]
|===
| Cloud Tiering license
| FabricPool license

| It is a _floating_ license that you can use across multiple on-premises ONTAP clusters. | It is a per-cluster license that you purchase and license for _every_ cluster.
| It is registered in the NetApp Console. | It is applied to individual clusters using System Manager or the ONTAP CLI.
| Tiering configuration and management is done through the Cloud Tiering service in the NetApp Console. | Tiering configuration and management is done through System Manager or the ONTAP CLI.
| Once tiering is configured, you can use the tiering service without a license for 30 days using the free trial. | Once configured, you can tier the first 10 TB of data for free.
|===

[[licenses]]
=== Transition to FabricPool licenses

If your licensed term is nearing the expiration date, or if your licensed capacity is reaching the limit, you'll be notified in Cloud Tiering as well as in the Console.

When you need to update your license, contact NetApp to purchase a FabricPool license. Once you have the new license, you can apply it to your clusters using System Manager or the ONTAP CLI.

Customer question:: Do they need to purchase a FabricPool license? Or will they get one automatically when they transition to the new licensing model if their contract is not up? I assume they need to purchase a new license, but I want to confirm.

[[apply-cloud-tiering-licenses-to-clusters-in-special-configurations]]
== Apply FabricPool licenses to clusters in special configurations

ONTAP clusters in the following configurations can use Cloud Tiering licenses, but the license must be applied in a different manner than single-node clusters, HA-configured clusters, clusters in Tiering Mirror configurations, and MetroCluster configurations using FabricPool Mirror:

* Clusters that are tiered to IBM Cloud Object Storage
* Clusters that are installed in "dark sites"

Customer question:: Do we need all of the categories of clusters listed here? Or just the first one? I'm out of my depth here.

=== Apply FabricPool licenses to existing clusters 



=== Apply FabricPool licenses to newly created clusters

